// ============ Auth Types ============
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";


// ============ Subscription Types ============
export const FETCH_SUBSCRIPTIONS_SUCCESS = "FETCH_SUBSCRIPTIONS_SUCCESS";
export const FETCH_SUBSCRIPTIONS_FAILURE = "FETCH_SUBSCRIPTIONS_FAILURE";


// ============ Search Types ============
export const SEARCHING_FOR_VIDEOS = "SEARCHING_FOR_VIDEOS";
export const FETCH_VIDEO_SEARCH_SUCCESS = "FETCH_VIDEO_SEARCH_SUCCESS";
export const FETCH_VIDEO_SEARCH_FAILURE = "FETCH_VIDEO_SEARCH_FAILURE";

export const SEARCHING_FOR_CHANNELS = "SEARCHING_FOR_CHANNELS";
export const FETCH_CHANNEL_SEARCH_SUCCESS = "FETCH_CHANNEL_SEARCH_SUCCESS";
export const FETCH_CHANNEL_SEARCH_FAILURE = "FETCH_CHANNEL_SEARCH_FAILURE";
